title: "Daniela Serrato | BI Portfolio"
description: "Business Intelligence Portfolio showcasing projects in data analysis, forecasting, and visualization."
baseurl: "" # Déjalo vacío para GitHub Pages
url: "https://danielaserrato.github.io" # Tu URL principal

markdown: kramdown
theme: null  # Desactiva los temas predeterminados
