title: "Daniela Serrato | BI Portfolio"
description: "Bilingual Business Intelligence Portfolio showcasing projects."
baseurl: ""  # Déjalo vacío
url: "https://danielaserrato.github.io"  # Reemplázalo con tu URL correcta
markdown: kramdown
theme: null

