# General site configuration
# Configuración básica
title: "Daniela Serrato | BI Portfolio"
description: "Bilingual Business Intelligence Portfolio showcasing projects."
baseurl: "/daniela-serrato-portafolio"  # El nombre del repositorio (si el sitio está alojado en un subdirectorio)
url: "https://danielaserrato.github.io"
markdown: kramdown  # Puedes usar kramdown para el formato de Markdown

# Configuración personalizada
logo: /assets/img/logo.png  # Asegúrate de que el logo exista en la carpeta de assets
show_downloads: true  # Activa un botón de descarga (si lo deseas)

# Google Analytics (opcional)
google_analytics:
  tracking_id: "G-QX0YV45X7B"  # Sustituye este valor con tu ID de seguimiento real

# Estilos personalizados (Sass o CSS)
sass:
  style: expanded  # Elige entre expanded o compressed CSS, si decides usar Sass

# Métodos de trabajo
theme: ""  # No usaremos ningún tema, dejamos el valor vacío
