title: "Daniela Serrato | BI Portfolio"
description: "Bilingual Business Intelligence Portfolio showcasing projects."
baseurl: "/daniela-serrato-portafolio"  # Incluye el nombre del repositorio
url: "https://danielaserrato.github.io"
markdown: kramdown
theme: null

